name: Build Pro App
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: subosito/flutter-action@v2
  with:
    flutter-version: '3.16.0'   <-- CORRECT
    
      - run: flutter pub get
      - run: flutter build apk --release --no-tree-shake-icons
      - uses: actions/upload-artifact@v3
        with:
          name: TeacherPro-APK
          path: build/app/outputs/flutter-apk/app-release.apk
          
